before_script:
  - hostname


.ncrc_build: &ncrc_build
  script:
    - source /opt/cray/pe/modules/default/init/bash
    - module rm cray-netcdf cray-hdf5 PrgEnv-intel PrgEnv-pgi PrgEnv-gnu PrgEnv-cray
    - module load PrgEnv-${COMPILER_FAMILY}
    - module swap ${COMPILER_NAME} ${COMPILER_NAME}/${COMPILER_VERSION}
    - module load cray-hdf5 cray-netcdf
    - mkdir local
    - git clone https://github.com/NOAA-GFDL/FMS.git FMS
    - cd FMS
    - autoreconf --install
    - ./configure --prefix=${CI_BUILDS_DIR}/local
    - make
    - make install
    - cd ..
    - autoreconf --install
    - ./configure
    - make


build:ncrc:intel19:debug:
  stage: build
  tags:
    - ncrc
  variables:
    CC: cc
    COMPILER_FAMILY: intel
    COMPILER_NAME: intel
    COMPILER_VERSION: 19.0.5.281
    FC: ftn
    F77: ftn
    FCFLAGS: "-I${CI_BUILDS_DIR}/local/include -O0"
    FFLAGS: "-I${CI_BUILDS_DIR}/local/include -O0"
    LDFLAGS: "-L${CI_BUILDS_DIR}/local/lib"
  <<: *ncrc_build
  artifacts:
    paths:
      - .libs/libatmos_phys.so
      - ./*.mod
